### ISSUE TITLE
Resnet 50

### ISSUE THREAD

**Issue by pedropgusmao** [NervanaSystems/caffe2neon#2]
Hi,

When testing the **tests/resnet/test_resnet.py** with ResNet-50 I get:
`
Traceback (most recent call last):
  File "tests/resnet/test_resnet.py", line 119, in <module>
    model.initialize(train)
  File "/home/standard/neon/neon/models/model.py", line 128, in initialize
    self.layers.allocate()
  File "/home/standard/neon/neon/layers/container.py", line 295, in allocate
    l.allocate()
  File "/home/standard/neon/neon/layers/container.py", line 634, in allocate
    l.allocate(shared_outputs=self.outputs)
  File "/home/standard/neon/neon/layers/container.py", line 293, in allocate
    alloc_layers[-1].allocate(shared_outputs)
  File "/home/standard/neon/neon/layers/layer.py", line 129, in allocate
    parallelism=self.parallelism)
  File "/home/standard/neon/neon/backends/backend.py", line 587, in iobuf
    out_tsr = shared if shared.shape == bufshape else shared.share(bufshape)
  File "/home/standard/neon/neon/backends/nervanagpu.py", line 595, in share
    raise ValueError("total size of new array must <= size of parent")
ValueError: total size of new array must <= size of parent
`

Am I doing something wrong?
Thanks

**Comment by nervetumer** [comment]
I pushed some changes.  I think the issue has to do with protobuf changes either in caffe or maybe because of changes in protobuf itself.  The type checking is failing when looking for a repeat field.  Found a couple other small issues/bugs along the way

**Comment by pedropgusmao** [comment]
Thanks, I was using ubuntu 14.04 with its respective version of google protobuf. I will try it with the 16.04 version now.
